In [ ]:
# UK Supermarket Data Preprocessing
This notebook loads, cleans, and prepares supermarket datasets for machine learning and time series analysis.

In [1]:
import pandas as pd
import numpy as np
import os

In [3]:
path = r"D:\uk-supermarket-forecasting\data\raw"
files = os.listdir(path)

dfs = []

for file in files:
    if file.endswith(".csv"):   # ✅ FIX HERE
        df = pd.read_csv(os.path.join(path, file))
        df["supermarket"] = file.split(".")[0]
        dfs.append(df)

# Combine
df_all = pd.concat(dfs, ignore_index=True)

print("Data loaded successfully")
df_all.head()

C:\Users\anuja\AppData\Local\Temp\ipykernel_28384\836155180.py:8: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(path, file))

Data loaded successfully

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
0,Aldi,3.09,0.14,unit,Mamia Ultra-fit Peppa Pig Nappy Pants 22 Pack/...,20240413,baby_products,False
1,Aldi,3.09,0.17,unit,Mamia Ultra-fit Peppa Pig Nappy Pants 18 Pack/...,20240413,baby_products,False
2,Aldi,3.59,0.09,unit,Mamia Ultra-fit Nappy Pants 40 Pack/Size 4,20240413,baby_products,False
3,Aldi,4.79,0.32,unit,Mamia Boy's Night Pants 15 Pack,20240413,baby_products,False
4,Aldi,4.79,0.32,unit,Mamia Girl's Night Pants 15 Pack,20240413,baby_products,False

In [5]:
print(files)

['Aldi.csv', 'Asda.csv', 'Morrisons.csv', 'Sainsburys.csv', 'Tesco.csv']

In [7]:
raw_combined = df_all.copy()
raw_combined.to_csv("raw_combined.csv", index=False, sep=';')

In [9]:
print(len(raw_combined))   # total rows
raw_combined.head()
raw_combined.tail()

9529242

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
9529237,Tesco,3.00,60.00,l,Simple Face Mask Detox & Brightening Clay Mask...,20240109,health_products,False
9529238,Tesco,3.00,10.90,l,Pantene Pro-V Hydrating Glow Quenching Hair Co...,20240109,health_products,False
9529239,Tesco,1.50,150.00,kg,Beyond Nootropic Blue Raspberry Lemonade Suppl...,20240109,health_products,False
9529240,Tesco,16.75,0.56,unit,Veet Expert Bikini & Underarm Wax Strips X30,20240109,health_products,False
9529241,Tesco,19.00,0.63,unit,Optibac Probiotics For Women 30 Caps,20240109,health_products,False

In [11]:
df_all["supermarket"].value_counts()

supermarket
Sainsburys    2600289
Asda          2456414
Tesco         2213611
Morrisons     1794065
Aldi           464863
Name: count, dtype: int64

In [13]:
df_all.sample(5)

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
5176260,Sainsburys,1.25,8.90,kg,Bahlsen PiCK UP! Milk Chocolate Biscuit Bars 5...,20240328,food_cupboard,False
4510335,Morrisons,7.99,0.80,kg,Indus Medium Chapatti Flour,20240120,food_cupboard,False
2451242,Asda,2.70,4.22,kg,Birds Eye Select Mixed Vegetables,20240127,frozen,False
2965676,Morrisons,16.00,16.00,l,Morrisons The Best Irish Cream Liqueur,20240411,drinks,True
1060259,Asda,1.08,1.44,kg,ASDA Frozen for Freshness Whole Green Beans 750g,20240322,frozen,True

In [15]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9529242 entries, 0 to 9529241
Data columns (total 8 columns):
 #   Column           Dtype
---  ------           -----
 0   supermarket      object
 1   prices_(£)       float64
 2   prices_unit_(£)  float64
 3   unit             object
 4   names            object
 5   date             int64
 6   category         object
 7   own_brand        object
dtypes: float64(2), int64(1), object(5)
memory usage: 581.6+ MB

In [17]:
df_all.isnull().sum()

supermarket          0
prices_(£)           7
prices_unit_(£)    524
unit               524
names               26
date                 0
category             0
own_brand           26
dtype: int64

In [19]:
df_all["date"] = pd.to_datetime(df_all["date"], errors="coerce")

In [21]:
df_all = df_all.dropna()

In [23]:
df_all["year"] = df_all["date"].dt.year
df_all["month"] = df_all["date"].dt.month
df_all["day"] = df_all["date"].dt.day
df_all["dayofweek"] = df_all["date"].dt.dayofweek

In [25]:
df_all.head()

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,year,month,day,dayofweek
0,Aldi,3.09,0.14,unit,Mamia Ultra-fit Peppa Pig Nappy Pants 22 Pack/...,1970-01-01 00:00:00.020240413,baby_products,False,1970,1,1,3
1,Aldi,3.09,0.17,unit,Mamia Ultra-fit Peppa Pig Nappy Pants 18 Pack/...,1970-01-01 00:00:00.020240413,baby_products,False,1970,1,1,3
2,Aldi,3.59,0.09,unit,Mamia Ultra-fit Nappy Pants 40 Pack/Size 4,1970-01-01 00:00:00.020240413,baby_products,False,1970,1,1,3
3,Aldi,4.79,0.32,unit,Mamia Boy's Night Pants 15 Pack,1970-01-01 00:00:00.020240413,baby_products,False,1970,1,1,3
4,Aldi,4.79,0.32,unit,Mamia Girl's Night Pants 15 Pack,1970-01-01 00:00:00.020240413,baby_products,False,1970,1,1,3

In [27]:
processed_df = df_all.copy()
processed_df.to_csv("processed_data.csv", index=False, sep=';')

In [29]:
df_all.to_csv("../data/processed/cleaned_data.csv", index=False)